# Generated by Django 5.1.3 on 2025-01-06 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='tags',
        ),
    ]
